export const ADD_CHAT = 'CHATLIST::ADD_CHAT';
export const DEL_CHAT = 'CHATLIST::DEL_CHAT';
export const ADD_MESSAGE = 'CHATLIST::ADD_MESSAGE';
export const DEL_MESSAGES = 'CHATLIST::DEL_MESSAGE';
